### ISSUE TITLE
can not use http keep-alive with http 1.1 LB

### ISSUE THREAD

**Issue by liulu721** [prebid/prebid-cache-java#106]
Some LoadBalancer implementation will remove "Connection" header when forwarding requests to upstream service (aka. prebid-cache-java). According to the implementation in PrebidServerResponseBuilder.java, both "isConnectionKeepAlive" and "isConnectionKeepAlive" are evaluated as true, and it seems "close" always work. This lead to a failure to use long connection, causing lower performance. I'm not sure if this is an issue to be fixed?

**Comment by bretg** [comment]
There's a PR in review for this and should be available with PBC 2.0 within the next month or so.
