### ISSUE TITLE
Aerospike server not running

### ISSUE THREAD

**Issue by rumanali123** [prebid/prebid-cache-java#82]
hi there,
I am configuring prebid cache java. I clone the git repo and follow the instructions as given in readme.md file.

<img width="1440" alt="Screenshot 2022-10-11 at 2 36 18 PM" src="https://user-images.githubusercontent.com/108808183/195054835-97c7ee27-a486-47ba-b3cf-36e350610a40.png">

when I run "sudo service aerospike start," this command says service not found. I already installed aerospike on my machine.

**Comment by bretg** [comment]
Did you resolve this issue @rumanali123 ? Any suggested docs updates as a result of your experience would be welcome.
